spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource

#这里记得添加依赖
#<dependency>
    #            <groupId>log4j</groupId>
    #            <artifactId>log4j</artifactId>
    #            <version>1.2.17</version>
    #        </dependency>

    filters: stat,wall,log4j
    jdbcUrl: jdbc:mysql://localhost:3306/mydate?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #    schema:
  #      - classpath:department.sql



#    protected volatile String username;
#    protected volatile String password;
#    protected volatile String jdbcUrl;
#    protected volatile String driverClass;
#    protected volatile int initialSize = 0;
#    protected volatile int maxActive = 8;
#    protected volatile int minIdle = 0;
#    protected volatile int maxIdle = 8;


test:
  username: lisi